--- #YAML:1.0
name:               EBook-Generator
version:            0.01
abstract:           Perl extension for creating EBooks from Websites.
author:
    - Tom Kirchner <tk@local>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:         0
    EBook::EPUB:          0
    File::Copy:           0
    File::Slurp:          0
    File::Temp:           0
    HTML::Entities:       0
    HTTP::Request:        0
    Image::Size:          0
    IO::File:             0
    LaTeX::Encode:        0
    LWP::UserAgent:       0
    MIME::Base64:         0
    Text::Wrap:           0
    XML::LibXML:          0
    XML::LibXML::XPathContext:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
